# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Harshika Tirpude
title: Project Coordinator
email: tirpudeharshika@gmail.com
website: www.euphoria1101.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: harshikatirpude
github_username: euphoria1101
//# stackoverflow_username: '00000001'
//# dribbble_username: jekyll
//# facebook_username: jekyll
//# flickr_username: jekyll
instagram_username: harshika_tirpude
linkedin_username: harshika tirpude
//# xing_username: jekyll
# pinterest_username: jekyll
//youtube_username: harshikatirpude
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-w.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello! My name is Harshika Tirpude, and I am a Project Coordinator with a passion for turning ideas into successful products. With experience in fast-paced startup environments, I specialize in Agile methodologies, sprint planning, and cross-functional team coordination to ensure smooth project execution.
  \nAt Hyve AI Labs (formerly Wisho), a UK-based startup, I led development teams, optimized workflows, and drove product launches, delivering high-impact mobile applications. My expertise lies in managing backlogs, streamlining communication between stakeholders, and ensuring timely, quality-driven project deliveries.
  \nI am PRINCE2 Agile Certified, which allows me to blend structured project management with Agile flexibility, ensuring teams stay focused, adaptable, and efficient.
  \n**Key Skills:** Agile & Scrum, Sprint Planning, Project Execution, API Testing, Stakeholder Communication, Risk & Resource Management.
  \n**Tools:** ClickUp, Jira, Figma, Postman, Google Workspace, Zoho, Notion, draw.io.

  

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Hyve AI Labs (formerly Wisho)
        sub_title: Project Coordinator
        caption: May 2023 - June 2024
        # link: Link to company (optional)
        # quote: >
        #   Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs I researched market trends, documented product requirements, managed backlogs, and planned sprints to ensure seamless project execution using Agile methodologies. I worked closely with the design team to create wireframes and flowcharts in Figma, contributing to the overall project success. As the leader of a team of ten in a startup environment, I collaborated with both frontend and backend teams, UI/UX designers, and handled quality testing for APIs and APKs, ensuring high standards. I also provided regular progress updates to the CTO. In addition to technical responsibilities, I supported administrative and recruitment tasks, such as tracking team leaves, scheduling interviews, communicating with candidates, and explaining project objectives during the hiring process.I researched market trends, documented product requirements, managed backlogs, and planned sprints to ensure seamless project execution using Agile methodologies. I worked closely with the design team to create wireframes and flowcharts in Figma, contributing to the overall project success. As the leader of a team of ten in a startup environment, I collaborated with both frontend and backend teams, UI/UX designers, and handled quality testing for APIs and APKs, ensuring high standards. I also provided regular progress updates to the CTO. In addition to technical responsibilities, I supported administrative and recruitment tasks, such as tracking team leaves, scheduling interviews, communicating with candidates, and explaining project objectives during the hiring process.
         
         - Led multiple product development cycles, ensuring smooth execution from concept to launch.
         - Managed Agile workflows, optimizing sprints, backlog prioritization, and cross-team collaboration.
         - Supported API testing & quality assurance, assisting in identifying and resolving issues to enhance application performance.
         - Facilitated stakeholder communication, aligning business needs with technical execution.
         - Assisted hiring & onboarding, ensuring smooth team expansion.
         
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Wisho
        link: github.com/euphoria1101/Projects/tree/main/wisho
        link_text: Wisho Release
        # additional_links:
        #   - title: sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Wisho is a mobile application where users can create and share heartfelt posts, wish for things they desire, and connect with others to fulfill their wishes by directly communicating with them. The app uses Flutter, Java, Firebase, and WebSocket to deliver an engaging, seamless experience for users as they share and act on each other’s aspirations.
        # description:
        #   | #
        #   A soon-to-be-launched social media mobile app where I coordinated the development and enforced rigorous quality assurance standards.

      - layout: top-middle
        title: Parking24
        link: github.com/euphoria1101/Projects/tree/main/parking24
        link_text: Parking24 Release
        # additional_links:
        #   - title: sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Parking24 is a mobile application designed for both users and parking space owners/managers. For users, it offers the convenience of finding, reserving, and paying for available parking spots across the UAE. For parking owners/managers, it provides a comprehensive platform to efficiently manage their parking spaces and track bookings, all enabled by Flutter, Java, and Firebase technology
        
        Hyve: Currently working on this e-commerce app for the UAE, managing project timelines, resource allocation, and ensuring seamless communication among team members and stakeholders.

      - layout: top-middle
        title: Hyve
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title: sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-…
        quote: >
          Hyve is a mobile application that empowers local UAE-based businesses by bringing them online and offering customers the ability to purchase everyday essentials from nearby shops. The app provides shop owners with a streamlined platform to manage their inventories and grow their digital presence, all while customers enjoy the ease of shopping locally from the comfort of their homes. The solution integrates Flutter, Java, Firebase, and WebSocket for an interactive and user-friendly experience.
        title: Gadget Reborn
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
        #   - title: sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
         Gadget Reborn is a platform dedicated to offering extended warranties and trusted repair services for mobile phones, ensuring continued protection and maintenance beyond the original manufacturer’s warranty. With both a mobile application and website, users can access a seamless experience to manage their extended coverage, schedule repairs, and make payments through an integrated gateway, all built using Flutter, Java, and other technologies.
  
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rashtrasant Tukdoji Maharaj Nagpur University, Nagpur
        caption: 2018 - 2022
        sub_title: Bachelor of Engineering (Computer Technology)
        description: |
          - Completed Bachelor of Engineering in Computer Technology from Rashtrasant Tukdoji Maharaj Nagpur University with a GPA of 83.5%.
          - Developed a Campus Recruitment System, facilitating interactive job vacancy management for students and placement officers.
          - Designed an Android-based Waste Food Management System, aiming to collect surplus food from hotels, restaurants, and individuals to distribute to those in need.
          - Authored a review on existing food management systems, proposing solutions to tackle food waste in India. Engaged in various extracurricular activities, including Event Management, co-organizing HORIZON-19, and active membership in the Rotaract Club of Priyadarshini College of Engineering.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
